### PR TITLE
Only link against `bfshell_plugin.so` and enable `pi` for SDE 9.7.0 build

### PR DESCRIPTION
**Pull request by Yi-Tseng**
`"barefoot-bin/lib/bfshell_plugin*",` can include some unexpected files when building with older version of SDEs which cause the build failed.

```
ERROR: /root/.cache/bazel/_bazel_root/1b07b1db06ec9ee22c71eac6f0bd4549/external/local_barefoot_bin/BUILD:13:11: in srcs attribute of cc_library rule @local_barefoot_bin//:bfsde: source file '@local_barefoot_bin//:barefoot-bin/lib/bfshell_plugin_bf_rt.la' is misplaced here (expected .cc, .cpp, .cxx, .c++, .C, .cu, .cl, .c, .h, .hh, .hpp, .ipp, .hxx, .h++, .inc, .inl, .tlh, .tli, .H, .tcc, .S, .s, .asm, .a, .lib, .pic.a, .lo, .lo.lib, .pic.lo, .so, .dylib, .dll, .o, .obj or .pic.o). Since this rule was created by the macro 'cc_library', the error might have been caused by the macro implementation
```

### CODE REVIEW

**Comment by Yi-Tseng** [comment]
Testing now with Stratum CI....

**Review by pudelkoM — APPROVED** [review]
LGTM

Do you have the errors somewhere? Would be good for future reference.

**Comment by Yi-Tseng** [comment]
> Do you have the errors somewhere? Would be good for future reference.

Yes, you can find the error here:
https://jenkins.stratumproject.org/view/Stratum%20Nightly%20Builds/job/stratum-bfrt-9.5.0/190/console

```
ERROR: /root/.cache/bazel/_bazel_root/1b07b1db06ec9ee22c71eac6f0bd4549/external/local_barefoot_bin/BUILD:13:11: in srcs attribute of cc_library rule @local_barefoot_bin//:bfsde: source file '@local_barefoot_bin//:barefoot-bin/lib/bfshell_plugin_bf_rt.la' is misplaced here (expected .cc, .cpp, .cxx, .c++, .C, .cu, .cl, .c, .h, .hh, .hpp, .ipp, .hxx, .h++, .inc, .inl, .tlh, .tli, .H, .tcc, .S, .s, .asm, .a, .lib, .pic.a, .lo, .lo.lib, .pic.lo, .so, .dylib, .dll, .o, .obj or .pic.o). Since this rule was created by the macro 'cc_library', the error might have been caused by the macro implementation
```

**Comment by Yi-Tseng** [comment]
I also need to update the build flag for SDE 9.7.0 to include `pi` library for stratum-bf

**Comment by Yi-Tseng** [comment]
All build pass, should be good to go
https://jenkins.stratumproject.org/view/Stratum%20Nightly%20Builds/

**Review by pudelkoM — APPROVED** [review]

**Pull request merged**
