### PR TITLE
Clean up SDE build file

### PR DESCRIPTION
**Pull request by pudelkoM**
Backport of a internal BFRT change. Since we don't know when/if the BFRT version will be merged, I'll backport as much as possible.

### CODE REVIEW

**Comment by Yi-Tseng** [comment]
Sounds good to me, should we also include `libbz2-dev` to our dev image?

**Comment by pudelkoM** [comment]
> Sounds good to me, should we also include `libbz2-dev` to our dev image?

Yes, we need it to build libarchive. Would you include it here? I'd do it in the `bfrt` branch so we get it once we need it.

**Comment by Yi-Tseng** [comment]
> > Sounds good to me, should we also include `libbz2-dev` to our dev image?
> 
> Yes, we need it to build libarchive. Would you include it here? I'd do it in the `bfrt` branch so we get it once we need it.

I think we can include it here so the CI will upload a new container image

**Comment by pudelkoM** [comment]
> > > Sounds good to me, should we also include `libbz2-dev` to our dev image?
> > 
> > 
> > Yes, we need it to build libarchive. Would you include it here? I'd do it in the `bfrt` branch so we get it once we need it.
> 
> I think we can include it here so the CI will upload a new container image

Done, also properly fixed in `bfrt`

**Pull request merged**
