### PR TITLE
Updating gRPC dependency to 1.31.0

### PR DESCRIPTION
**Pull request by bocon13**

### CODE REVIEW

**Comment by bocon13** [comment]
```INFO: From Compiling external/com_github_grpc_grpc/src/core/lib/iomgr/exec_ctx.cc [for host]:
external/com_github_grpc_grpc/src/core/lib/iomgr/exec_ctx.cc:61:11: warning: implicit conversion from 'long' to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Wimplicit-const-int-float-conversion]
  if (x > GRPC_MILLIS_INF_FUTURE) return GRPC_MILLIS_INF_FUTURE;
        ~ ^~~~~~~~~~~~~~~~~~~~~~
external/com_github_grpc_grpc/src/core/lib/iomgr/exec_ctx.h:39:32: note: expanded from macro 'GRPC_MILLIS_INF_FUTURE'
#define GRPC_MILLIS_INF_FUTURE INT64_MAX
                               ^~~~~~~~~
/usr/include/stdint.h:163:22: note: expanded from macro 'INT64_MAX'
# define INT64_MAX              (__INT64_C(9223372036854775807))
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/stdint.h:145:24: note: expanded from macro '__INT64_C'
#  define __INT64_C(c)  c ## L
                        ^~~~~~
<scratch space>:246:1: note: expanded from here
9223372036854775807L
^~~~~~~~~~~~~~~~~~~~
external/com_github_grpc_grpc/src/core/lib/iomgr/exec_ctx.cc:75:11: warning: implicit conversion from 'long' to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Wimplicit-const-int-float-conversion]
  if (x > GRPC_MILLIS_INF_FUTURE) return GRPC_MILLIS_INF_FUTURE;
        ~ ^~~~~~~~~~~~~~~~~~~~~~
external/com_github_grpc_grpc/src/core/lib/iomgr/exec_ctx.h:39:32: note: expanded from macro 'GRPC_MILLIS_INF_FUTURE'
#define GRPC_MILLIS_INF_FUTURE INT64_MAX
                               ^~~~~~~~~
/usr/include/stdint.h:163:22: note: expanded from macro 'INT64_MAX'
# define INT64_MAX              (__INT64_C(9223372036854775807))
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/stdint.h:145:24: note: expanded from macro '__INT64_C'
#  define __INT64_C(c)  c ## L
                        ^~~~~~
<scratch space>:248:1: note: expanded from here
9223372036854775807L
^~~~~~~~~~~~~~~~~~~~
2 warnings generated.
```

**Comment by Yi-Tseng** [comment]
Can we use https://github.com/grpc/grpc/archive/v1.32.0.tar.gz ?

**Comment by bocon13** [comment]
> Can we use https://github.com/grpc/grpc/archive/v1.32.0.tar.gz ?

Yes, I'll make the update

**Comment by bocon13** [comment]
This may break grpc_py_deps: `The repository '@grpc_py_deps' could not be resolved.`

**Comment by pudelkoM** [comment]
> This may break grpc_py_deps: `The repository '@grpc_py_deps' could not be resolved.`

Add
```bazel
pip_import(
   name = "grpc_py_deps",
   requirements = "@build_stack_rules_proto//python:requirements.txt",
)
```
to `deps.bzl`?

**Comment by Yi-Tseng** [comment]
I think there is a way to not use the build_stack_rules_proto (we might also want to remove this one since it is not maintained for 5 months)
You can find change here:
https://github.com/stratum/stratum/pull/341/files

**Review by Yi-Tseng — APPROVED** [review]

**Comment by bocon13** [comment]
Need to update Mininet Dockerfile as well

**Comment by bocon13** [comment]
superseded by #350

**Pull request closed without merging**
