### PR TITLE
Update APS Networks switches in the README

### PR DESCRIPTION
**Pull request by bocon13**
Renaming Stordis to APS Networks

### CODE REVIEW

**Comment by pudelkoM** [comment]
Do we also want to rename files and folders like `stratum/hal/config/x86-64-stordis-bf6064x-t-r0`? There are also some strings in ChassisConfigs.

**Comment by bocon13** [comment]
> Do we also want to rename files and folders like `stratum/hal/config/x86-64-stordis-bf6064x-t-r0`? There are also some strings in ChassisConfigs.

That requires some changes outside of Stratum as well (e.g. in ONL) that I don't really want to worry about. Maybe we can ask them to comment on their plans here.

**Comment by pudelkoM** [comment]
> That requires some changes outside of Stratum as well (e.g. in ONL)

Good point. Even if there will be a new platform string, it's probably better to duplicate than to rename to keep compat with older devices.

**Review by pudelkoM — APPROVED** [review]
LGTM.

Change git commit message to "Update APS ..."?

**Pull request merged**
