### PR TITLE
Update OpenNSA to version 6.5.19.1

### PR DESCRIPTION
**Pull request by pudelkoM**
This PR updates the OpenNSA dependency to version 6.5.19.1.

@abhilashendurthi did some testing in PR #369 and did not find any issues.

### CODE REVIEW

**Review by bocon13 — DISMISSED** [review]
lgtm

**Comment by pudelkoM** [comment]
> changed the base branch from master to fix-yang-tofino-platform-enum 3 hours ago

???

**Comment by bocon13** [comment]
It did, so I changed the base branch to clean up the diff for review.

**Comment by pudelkoM** [comment]
oh, my mistake when creating the branch.

**Comment by ux-8** [comment]
> This PR updates the OpenNSA dependency to version 6.5.19.1.
> 
> @abhilashendurthi did some testing in PR #369 and did not find any issues.

**Pull request merged**
