### PR TITLE
Push tools image to Aether harbor registry

### PR DESCRIPTION
**Pull request by pudelkoM**
With the docker.io rate limits and the depreciation of the bf-pipeline-builder image, I decided to upload the `stratum-tools` image to the Aether registry as well. It can be found here: https://registry.aetherproject.org/harbor/projects/4/repositories/stratum-tools. ONF projects should use that image going forward.

Pros of pushing the image from here (circleci):
- Full control over build flags and tags
- Easy to change, update and maintain in one atomic commit

Cons:
- Increased risk of credential leak (will be addressed in the future with project specific credentials)
- Two names for the same image `tost/stratum-tools` and `stratumproject/stratum-tools`

Any other concerns?

### CODE REVIEW

**Comment by stolsma** [comment]
I hope this doesn't mean that in the future access to Stratum container images will become for ONF members only as is the case for the Aether registry. That would be a real bummer for independent developers....😔

**Comment by pudelkoM** [comment]
> @bocon13 @pudelkoM I hope this doesn't mean that in the future access to Stratum container images will become for ONF members only as is the case for the Aether registry. That would be a real bummer for independent developers....😔

Thanks for voicing your concerns. Here are some points to hopefully dispel them:
- We pushing the image to an **additional** registry 
- This job would otherwise run on our internal jenkins CI (See https://github.com/stratum/stratum-ci)
- The source code to build the images is still available

**Review by bocon13 — APPROVED** [review]
lgtm

**Comment by bocon13** [comment]
@stolsma, thanks for reaching out! Nothing is changing on the public Docker Hub side. It's our intention to keep Stratum source code fully open and to continue to publish public images for new releases as we've done for the past ones. :)

**Pull request merged**
