### PR TITLE
[stratum-bcm] Add support for VLAN tagged traffic

### PR DESCRIPTION
**Pull request by miguelbf-alb**
## Description

Currently, stratum-bcm is not able to handle vlan tagged traffic unless a reactive approach is employed (by forwarding all traffic to the controller using, for example, the fwd application). The root cause of the problem is the fact that neither the VLAN is created anywhere in the codebase nor the respective port bitmaps are associated to the respective VLAN. This PR tries to solve the issue by creating (or removing) the VLANS on-demand whenever flow rules which reference a given VLAN are added (or removed) to/from the `my_station_table`. The VLAN id was already used by `BcmL2Manager::InsertMyStationEntry` but not exposed to the p4 pipeline.
Previously, the only way to achieve traffic forwarding would be to manually configure the VLANS in the bcm cli (e.g. for opennsa):

```
>> vlan create 10
>> vlan add 10 portBitMap=ce16,ce20
```

Superseeds: https://github.com/stratum/stratum/pull/782 (exactly the same code)

## How Has This Been Tested?

This was tested with the scenario illustrated below both with the Opennsa and SDKLT versions of stratum_bcm:

```
                 ┌──────────────────┐
                 │                  │
┌─────────┐      │                  │     ┌────────────┐
│    h1   │      │  stratum-bcm     │     │     h2     │
│         ├──────┤                  ├─────┤            │
└─────────┘      │                  │     └────────────┘
                 │                  │
10.66.5.2        └──────────────────┘      10.66.5.3

00:00:00:00:00:01                          00:00:00:00:00:02

 VLAN=10                                    VLAN=10
```

Using p4runtime-shell the following entries were created:

```
my_station_table:

H1 -> H2
t2=table_entry["ingress.my_station_table"](action="NoAction")
t2.match["hdr.ethernet.dst_addr"]="00:00:00:00:00:02"
t2.match["hdr.vlan_tag[0].vid"]="10"
t2.priority=50000
t2.insert()

H2 -> H1

t2=table_entry["ingress.my_station_table"](action="NoAction")
t2.match["hdr.ethernet.dst_addr"]="00:00:00:00:00:01"
t2.match["hdr.vlan_tag[0].vid"]="10"
t2.priority=50000
t2.insert()

punt/ACL table:

t=table_entry["ingress.punt.punt_table"](action="ingress.punt.set_egress_port")
t.match["hdr.ipv4_base.dst_addr"]="10.66.5.2"
t.match["hdr.vlan_tag[0].vid"]="10"
t.action["port"]="17"
t.priority=50000
t.insert()

t2=table_entry["ingress.punt.punt_table"](action="ingress.punt.set_egress_port")
t2.match["hdr.ipv4_base.dst_addr"]="10.66.5.3"
t2.match["hdr.vlan_tag[0].vid"]="10"
t2.action["port"]="102"
t2.priority=50000
t2.insert()
```

Traffic forwarding between both hosts was confirmed after installing the aforementioned rules. Removing the flows from `my_station_table` was also confirmed to remove the respective VLAN from the switch.

Regards

### CODE REVIEW

**Comment by pudelkoM** [comment]
It's ok to ignore the formatting issue with the SdkWrapper, addressing this here would blow up the diff.

**Comment by enen92** [comment]
Jfyi I am trying to get the cla issue sorted out internally, I will ping back when this is ready for review. Apologies for the delay.

**Comment by miguelbf-alb** [comment]
JFYI I'm trying to sort out the CLA issue (both internally and with the ONF). Looks like it has been signed from our side but not yet approved/available. I will ping back when this is ready for review. Apologies for the delay.

**Comment by pierventre** [comment]
retest this please

**Comment by miguelbf-alb** [comment]
@pudelkoM @bocon13 sorry for the delay, the CLA issue has been finally sorted out. This is okay for review now.
I'll be submitting a few more patches for stratum-bcm on the next days. Please, let me know if I need to change anything.
Regards

**Pull request closed without merging**
