### PR TITLE
Update PI and BMv2 versions

### PR DESCRIPTION
**Pull request by bocon13**
Add veth_setup.sh and veth_teardown.sh to build Docker image
Update BMv2 reference chassis config will all 9 ports

### CODE REVIEW

**Comment by bocon13** [comment]
@ccascone @pudelkoM @Yi-Tseng any objections to bumping the versions on PI and BMv2?

Also, I noticed that the PI version imported by Bazel and the version that we install into the build container are a little out of sync.

**Comment by pudelkoM** [comment]
> @ccascone @pudelkoM @Yi-Tseng any objections to bumping the versions on PI and BMv2?
> 
> Also, I noticed that the PI version imported by Bazel and the version that we install into the build container are a little out of sync.

No concern from my side. Last time we updated PI it broke a few assumptions clients (e.g. ONOS) made about bmv2.

**Comment by ccascone** [comment]
LGTM

**Comment by bocon13** [comment]
Looks like the diff is pretty small. There is a fix in both PI and BMv2 for meters, so that may be the only place that we could see anything different.

**Review by pudelkoM — APPROVED** [review]

**Pull request merged**
