### PR TITLE
Add SFP28 support

### PR DESCRIPTION
**Pull request by habeebmohammed**
fix the issue https://github.com/stratum/stratum/issues/164
Added the macros for SFP28.

verified with 25G AOC cable.
No error "invalid sfptype" is seen and links can come up fine.

Attached is the verify log
[sfp28_log.txt](https://github.com/stratum/stratum/files/4341067/sfp28_log.txt)

### CODE REVIEW

**Comment by habeebmohammed** [comment]
I wanted to submit new pull request for below commit ID. However, it does not allow with one pull request open.
commit 421db4004b07e2d07acf4c4d94fb82cefc96c4b4 -correct pn_swap settings in platform config for d10056

**Comment by pudelkoM** [comment]
Can you also paste the exact error message? I suspect there might be something wrong with the platform/driver, if ONLP does not report a SFP type (`Type` column in `onlps sfp inventory`).

**Comment by bocon13** [comment]
@habeebmohammed you should be able to update your pull request by pushing (using --force if needed) the new code to this branch: habeebmohammed:master

**Comment by habeebmohammed** [comment]
E0318 17:41:38.931422    46 sfp_adapter.cc:96] StratumErrorSpace::ERR_INVALID_PARAM: Invalid sfptype.
E0318 17:41:38.931495    46 bf_chassis_manager.cc:741] Failure in TransceiverEventHandler: StratumErrorSpace::ERR_INVALID_PARAM: Invalid sfptype.

**Comment by habeebmohammed** [comment]
Links are UP in my case though I see an "Invalid sfptype" error. 
Also, I see "type" is blank in our case.
root@localhost:~# onlps sfp inventory
Port  Type    Module          Media   Status  Len    Vendor            Model             S/N
----  ------  --------------  ------  ------  -----  ----------------  ----------------  ----------------
   1          10GBASE-SR      Fiber                  FINISAR CORP.     FTLX8571D3BCL     AJG00WS
   2          10GBASE-SR      Fiber                  FINISAR CORP.     FTLX8571D3BCL     AJF0FJX
   3          25GBASE-AOC     Fiber           5m     FINISAR CORP      FCBG125SD1C05     WXC0J4B
   4          25GBASE-AOC     Fiber           5m     FINISAR CORP      FCBG125SD1C05     WXC0J4B
   5          25GBASE-AOC     Fiber           5m     FINISAR CORP      FCBG125SD1C05     WXC0J4C
   6          25GBASE-AOC     Fiber           5m     FINISAR CORP      FCBG125SD1C05     WXC0J4C
   7

**Comment by habeebmohammed** [comment]
> Can you also paste the exact error message? I suspect there might be something wrong with the platform/driver, if ONLP does not report a SFP type (`Type` column in `onlps sfp inventory`).

In our onlp "Type" column is blank but I see an error only for optic, not for DAC cable or QSFP. Do you know the reason?

**Comment by pudelkoM** [comment]
> In our onlp "Type" column is blank but I see an error only for optic, not for DAC cable or QSFP. Do you know the reason?

I think the `Type` field might only be needed in the Broadcom code path. It would be nice to have  complete platform support, but if your changes fix the error, then we should go ahead.

**Pull request merged**
